package me.Salt.Util;

/**
 * Created by Salt001 on 20/11/2016.
 */
public enum JLogComponent { //List of 'components' that get logged, aka, events that get logged

    GROUP_JOIN_EVENT,
    GUILD_BAN_EVENT,
    GUILD_JOIN_EVENT,
    GUILD_UNBAN_EVENT,
    FRIEND_ADDED_EVENT,
    USER_BLOCKED_EVENT,
    GROUP_USER_JOIN_EVENT,
    CALL_VOICE_JOIN_EVENT,
    USER_UNBLOCKED_EVENT,
    GROUP_UPDATE_ICON_EVENT,
    GROUP_UPDATE_NAME_EVENT,
    GROUP_UPDATE_OWNER_EVENT,
    CALL_VOICE_SELF_MUTE_EVENT,
    FRIEND_REQUEST_SENT_EVENT,
    GROUP_MESSAGE_DELETE_EVENT,
    GROUP_MESSAGE_UPDATE_EVENT,
    CALL_VOICE_SELF_DEAFEN_EVENT,
    FRIEND_REQUEST_IGNORED_EVENT,
    FRIEND_REQUEST_CANCELED_EVENT,
    ROLE_CREATE_EVENT,
    ROLE_DELETE_EVENT,
    USER_TYPING_EVENT,
    STATUS_CHANGE_EVENT,
}
