package me.Salt.Util;

public enum Permissions {
//User banning
BAN_USER_TEMP,
BAN_USER_PERM,
BAN_USER_BY_NAME,
BAN_USER_BY_ID,
BAN_MULTIPLE_USERS_BY_NAME,
BAN_MULTIPLE_USERS_BY_ID,
BAN_USER_CROSSGUILD_PERM,
BAN_USER_CROSSGUILD_TEMP,
BAN_USER_BY_ROLE,

//User muting
MUTE_USER_TEMP,
MUTE_USER_PERM,
MUTE_USER_BY_NAME,
MUTE_USER_BY_ID,
MUTE_MULTIPLE_USERS_BY_NAME,
MUTE_MULTIPLE_USERS_BY_ID,
MUTE_USER_CROSSGUILD_PERM,
MUTE_USER_CROSSHUILD_TEMP,
MUTE_USER_BY_ROLE,

//VoiceChannel Banning
BAN_CHANNEL_TEMP
BAN_CHANNEL_PERM
}
