package me.Salt.JPI.Entities.Games.CardsAgainstDiscord.Util;

/**
 * Created by 15122390 on 07/12/2016.
 */
public enum Perk {
    RANDOM_CARD_TRADE,
    SHOW_ENTIRE_DECK,
    REMOVE_RANDOM_CARD,
    PREVENT_NEXT_ROUND_PLAY,
    FORCE_BLACK_WHITE_CARD_TRADE,
    POINT_VOTE,
    VIEW_NEXT_BLACK_CARD,
    VIEW_NEXT_WHITE_CARD,
    DECK_RECYCLE,
    CHOSEN_RANDOM_CARD_SWAP,
    RANDOM_DECK_SWAP,
    MASS_CARD_TRADE,
    SILENT_POINT_SCRAMBLE,
    LOSING_SCORE_BOOST,
    SHORTENED_TIMER,
    FORCE_BLACK_CARD_PACK,
    TOTAL_SELECTED_POINT_REMOVAL,
    PLUS1_PERK_SPIN
}
